App\Model\Dto\WeatherAPIResponse:
    attributes:
        name:
            groups: ['weather']
        dt:
            groups: ['weather']
        main:
            groups: ['weather']
        sys:
            groups: ['weather']